[cols="",]
|===============================================================
a|
Description:

In this section you will bootstrap your Kubic Kubernetes cluster

|===============================================================

==== Task 1: Set up Kubic-Master

. Login into the *Kubic-Master* VM if you have not already done so:
+
[gray]*Userid*: *root*
+
[gray]*Password*: *[your root password]*
. Run the following command to configure this as a Kubernetes master
node:
+
 kubeadm init --cri-socket=/var/run/crio/crio.sock \ --pod-network-cidr=10.244.0.0/16
+
You should see some output and at the end, you will see this:
+
You can now join any number of machines by running the following on each
node as root:
+
 kubeadm join 10.0.2.11:6443 --token …
+
[IMPORTANT]
Save this command. You will need it later!

==== Task 2: (optional) Add a second network interface to Kubic-Master VM

. Power off the Kubic-Master VM
+
 halt -p

. From the main Virtualbox screen, choose the *Kubic-Master VM* and
click on Settings
. Click on the Network icon
. Click on the Adaptor 2 tab
+
Change Attached to to Bridged Adaptor
+
Name should automatically change to whatever physical network adaptor
you are using.
. From the main Virtualbox screen, choose the *Kubic-Master* VM and
click on the down arrow next to the start icon. Click on Detachable
Start
. Log into the command line:
+
Userid: *root*
+
Password: *[your root password]*
. Start the curses version of yast to configure networking on the new
nic
+
 yast2 lan

. Use the *F4* key on your keyboard to edit the new nic
. Click on *alt y* on your keyboard to change this nic to DHCP. If
your network does not have DHCP, set a static IP instead.
. Click on *F10* on your keyboard to exit this screen
. Click on *F10* on your keyboard to exit yast
. Find your new IP addresses
+
 ip a
+
You should now be able to log into the Kubic-Master using the terminal
or application of your choice. You can also now copy and paste from this
book.

==== Task 3: Set up the Kubic-Workers

. Login to the Kubic-Worker1 VM if you have not already done so:
+
Userid: *root*
+
Password: *[your root password]*
. Run the output command from Task 1 and add
+
 --cri-socket=/var/run/crio/crio.sock
+
to the end of the command +
. Repeat this task for every worker VM

==== Task 4: Set up the kubectl

. On the *Kubic-Master* VM, copy and set up the config file so that
kubectl can interact with the cluster:
+
 mkdir -p $HOME/.kube
 sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
 sudo chown $(id -u):$(id -g) $HOME/.kube/config

. Check on your nodes
+
 kubectl get nodes
+
You should have 3 nodes. All of them should be in a NotReady status

==== Task 5: Set up Flannel

. Run the following command to install flannel on your cluster:
+
 kubectl apply -f https://0y.at/kubicflannel
. Check on your nodes
+
watch kubectl get nodes
+
In 1-2 minutes all of them should be in a Ready status. Click on *Ctrl
c* on your keyboard to exit this screen.
+

You now have a fully functional Kubernetes cluster! You can add more
worker nodes at any time and then bootstrap them in like you did above.

[cols="",]
|=======================================================================
a|
Summary:

In this section you completed your Kubic Kubernetes cluster. It is now
fully functional and ready to be used.

|=======================================================================

(End of Exercise)
